### ISSUE TITLE
Missing Json file?

### ISSUE THREAD

**Issue by lxtGH** [alirezazareian/ovr-cnn#2]
Hi! Thanks for opensourcing the code. I wonder where are the two json files? @alirezazareian 

 mscoco_seen_classes.json and mscoco_unseen_classes.json'?

**Comment by alirezazareian** [comment]
You can download them from here:

https://github.com/alirezazareian/ovr-cnn/blob/master/mscoco_seen_classes.json
https://github.com/alirezazareian/ovr-cnn/blob/master/mscoco_unseen_classes.json

These files were provided by an earlier paper: https://arxiv.org/abs/1804.04340

**Comment by lxtGH** [comment]
Thank you!

**Comment by anosorae** [comment]
The link to download the two json file was 404 not found now, can you give another link?

**Comment by alirezazareian** [comment]
Thanks for noticing. Links were updated above.

**Comment by Atlantisming** [comment]
Hi, thank you for your opensourcing @alirezazareian .And Thanks for your noticing @lxtGH . 

I tried to create the new annotation json file follow [this notebook](https://github.com/alirezazareian/ovr-cnn/blob/master/ipynb/003.ipynb) and not found the file '../datasets/coco/zero-shot/glove.6B.300d.txt'.

Do I miss something needed ? Thanks a lot.

**Comment by qinliuliuqin** [comment]
It can be downloaded here: http://nlp.stanford.edu/data/glove.6B.zip
