### ISSUE TITLE
about create ov-coco annotation

### ISSUE THREAD

**Issue by Atlantisming** [alirezazareian/ovr-cnn#24]
## 🚀 Feature
I tried to create the new annotation json file follow [this notebook](https://github.com/alirezazareian/ovr-cnn/blob/master/ipynb/003.ipynb) and not found the file `'../datasets/coco/zero-shot/glove.6B.300d.txt'`.

Do I miss something needed?Thanks

**Comment by alirezazareian** [comment]
Those are pretrained GloVE embeddings, which can be downloaded [here](https://github.com/stanfordnlp/GloVe)

**Comment by Atlantisming** [comment]
Thanks
