### ISSUE TITLE
About preparing the training dataset

### ISSUE THREAD

**Issue by 18290888765** [alirezazareian/ovr-cnn#27]
## ❓ Questions and Help
Hello blogger, in the 003.ipynb file, there is a glove.6B.300d.txt file, how do you get this file?

**Comment by Atlantisming** [comment]
https://github.com/alirezazareian/ovr-cnn/issues/24#issue-1484550427

**Comment by alirezazareian** [comment]
You can find it [here](https://huggingface.co/stanfordnlp/glove/resolve/main/glove.6B.zip)
