### ISSUE TITLE
Segmentation Mask?

### ISSUE THREAD

**Issue by lxtGH** [alirezazareian/ovr-cnn#3]
After I pretrain the model using the caption dataset, I train the second stage where I meet such error. 
Why there are segmentation mask?

![image](https://user-images.githubusercontent.com/17202268/113234150-4f3bb580-92d3-11eb-9af6-1e877a72b759.png)

**Comment by lxtGH** [comment]
solved by removing mask loading

**Comment by ZeyuMa-Uestc** [comment]
> solved by removing mask loading

Hi I meet this bug, can you tell me how to remove mask loading, thanks!
