### ISSUE TITLE
 Pretrained Models in the first stage

### ISSUE THREAD

**Issue by lxtGH** [alirezazareian/ovr-cnn#4]
## ❓ Questions and Help
Hi！Again, thanks for the code.

Could you release the pretrained models in the first stage for reference?

I follow the two stage pipeline. First train the model using COCO caption then training with coco zero setting.

 However, I can not get the right results of the paper.

There is a huge drop on seen class mAP.

@alirezazareian

**Comment by alirezazareian** [comment]
[Here](https://www.dropbox.com/s/cao3goqnrzb7bn5/model_pretrained.pth?dl=0) is the pretrained model checkpoint. Please let me know if this doesn't resolve the issue.

**Comment by lxtGH** [comment]
Hi!  Thanks for your reply.  The gap has been resolved.
