### ISSUE TITLE
How to reproduce your results.

### ISSUE THREAD

**Issue by lxtGH** [alirezazareian/ovr-cnn#5]
@alirezazareian . Hi!  Thanks for opensourcing your code.
I follow the two step training procedure. However, the results are far away from your paper results.
I try many setting in the second stage but I still get inferior results.

**Comment by alirezazareian** [comment]
Could you please share more details, e.g. the exact numbers you are getting and the entire output log for both pretraining and fine-tuning? Can you reproduce the results if you use the shared [checkpoint](https://github.com/alirezazareian/ovr-cnn#pretrained-models)?

**Comment by lxtGH** [comment]
Thanks for your reply.
Still a little gap. 
Experiment results: 46.6, 26.9,  Generalized: 46.6, 22.1 
Paper :  46.8 , 27.5,  Generalized: 46.0, 22.8

**Comment by lxtGH** [comment]
Could you help me on how to reproduce such pretrained model ? Could you release the pretrained log for reference.
