### ISSUE TITLE
Why fine tuning takes more as compared to pretraining

### ISSUE THREAD

**Issue by mmaaz60** [alirezazareian/ovr-cnn#8]
Hi,

As mentioned in the paper, the pretraining stage took around 10 hours and fine tuning on COCO took around 18 hours on 8 V-100 GPUs. Why is the fine tuning taking more time as compared to pretraining?

**Comment by lxtGH** [comment]
In my opinion, fine tuning takes more iteration.

**Comment by mmaaz60** [comment]
> In my opinion, fine tuning takes more iteration.

If that so then fine-tuning should take more time compared to detection training, right? But in the paper it is mentioned that the detection training took more as compared to the fine-tuning.

**Comment by alirezazareian** [comment]
Fine-tuning is done based on a Faster R-CNN model, which includes a region proposal network, non-max suppression, etc., which involves a lot of extra computation for hundreds of bounding boxes for each image. Pretraining is faster as it uses a simple CNN backbone without any bounding boxes.
